//! Wayland Pointer, Keyboard Focus & Drag Input Dispatcher (Zero-Eww)
//! Provides spatial hit-testing, layer resolution, pointer events, window focus,
//! and keyboard shortcut matching.

#[path = "settings_controller.rs"]
pub mod settings_controller;

use serde::{Deserialize, Serialize};

/// Represents a rectangular region for spatial hit testing.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct Rect {
    pub x: f64,
    pub y: f64,
    pub width: f64,
    pub height: f64,
}

impl Rect {
    pub fn new(x: f64, y: f64, width: f64, height: f64) -> Self {
        Self { x, y, width, height }
    }

    /// Spatial bounds collision check: left <= x <= right && top <= y <= bottom
    pub fn contains(&self, x: f64, y: f64) -> bool {
        let left = self.x;
        let right = self.x + self.width;
        let top = self.y;
        let bottom = self.y + self.height;

        x >= left && x <= right && y >= top && y <= bottom
    }
}

/// An interactive rectangular region on screen.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct HitBox {
    pub id: String,
    pub rect: Rect,
    pub cursor_shape: String,
    pub on_click: Option<String>,
    pub z_index: i32,
}

impl HitBox {
    pub fn new(id: impl Into<String>, rect: Rect, cursor_shape: impl Into<String>, on_click: Option<String>) -> Self {
        Self {
            id: id.into(),
            rect,
            cursor_shape: cursor_shape.into(),
            on_click,
            z_index: 0,
        }
    }

    pub fn with_z_index(mut self, z_index: i32) -> Self {
        self.z_index = z_index;
        self
    }
}

/// Pointer input events generated by Wayland seat dispatcher.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum PointerEvent {
    Motion(f64, f64),
    ButtonPress(u32),
    ButtonRelease(u32),
    AxisScroll(f64, f64),
}

/// Keyboard input events.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum KeyEvent {
    /// Press(keycode, modifiers_bitfield)
    Press(u32, u32),
    /// Release(keycode)
    Release(u32),
}

/// Window lifecycle and focus state events.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum WindowEvent {
    FocusIn,
    FocusOut,
    CloseRequested,
}

/// Hover state transition events.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum HoverEvent {
    MouseEnter(String),
    MouseLeave(String),
}

/// Modifier bitflags for keyboard shortcuts.
pub struct Modifiers;

impl Modifiers {
    pub const SHIFT: u32 = 1 << 0;
    pub const CTRL: u32 = 1 << 1;
    pub const ALT: u32 = 1 << 2;
    pub const SUPER: u32 = 1 << 3;
}

/// Keyboard shortcut representation.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct Shortcut {
    pub keycode: u32,
    pub modifiers: u32,
}

impl Shortcut {
    pub fn new(keycode: u32, modifiers: u32) -> Self {
        Self { keycode, modifiers }
    }

    /// Parse human readable shortcut string like "Ctrl+Shift+T" or "Super+Q".
    pub fn parse(spec: &str) -> Result<Self, String> {
        let parts: Vec<&str> = spec.split('+').map(|s| s.trim()).collect();
        if parts.is_empty() {
            return Err("Empty shortcut specifier".to_string());
        }

        let mut mods = 0u32;
        let mut keycode = None;

        for part in parts {
            match part.to_lowercase().as_str() {
                "ctrl" | "control" => mods |= Modifiers::CTRL,
                "shift" => mods |= Modifiers::SHIFT,
                "alt" => mods |= Modifiers::ALT,
                "super" | "win" | "meta" => mods |= Modifiers::SUPER,
                key => {
                    if keycode.is_some() {
                        return Err(format!("Multiple keycodes specified in '{}'", spec));
                    }
                    // Simple parse or common ASCII mapping
                    if key.len() == 1 {
                        let ch = key.chars().next().unwrap().to_ascii_uppercase();
                        keycode = Some(ch as u32);
                    } else if let Ok(num) = key.parse::<u32>() {
                        keycode = Some(num);
                    } else {
                        // Fallback simple hash for named keys like "Return", "Space", "Tab"
                        let code = match key {
                            "return" | "enter" => 13,
                            "tab" => 9,
                            "space" => 32,
                            "escape" | "esc" => 27,
                            _ => return Err(format!("Unknown key name '{}'", key)),
                        };
                        keycode = Some(code);
                    }
                }
            }
        }

        let keycode = keycode.ok_or_else(|| format!("No keycode found in shortcut '{}'", spec))?;
        Ok(Self { keycode, modifiers: mods })
    }

    pub fn matches(&self, key_event: &KeyEvent) -> bool {
        match key_event {
            KeyEvent::Press(code, mods) => *code == self.keycode && *mods == self.modifiers,
            _ => false,
        }
    }
}

/// Matcher to store and evaluate keyboard shortcut bindings.
#[derive(Debug, Default, Clone)]
pub struct ShortcutMatcher {
    bindings: Vec<(Shortcut, String)>,
}

impl ShortcutMatcher {
    pub fn new() -> Self {
        Self { bindings: Vec::new() }
    }

    pub fn bind(&mut self, shortcut: Shortcut, action: impl Into<String>) {
        self.bindings.push((shortcut, action.into()));
    }

    pub fn bind_str(&mut self, spec: &str, action: impl Into<String>) -> Result<(), String> {
        let sc = Shortcut::parse(spec)?;
        self.bind(sc, action);
        Ok(())
    }

    pub fn match_event(&self, event: &KeyEvent) -> Option<&str> {
        for (shortcut, action) in &self.bindings {
            if shortcut.matches(event) {
                return Some(action.as_str());
            }
        }
        None
    }
}

/// HitTestManager maintains active hitboxes, calculates top-most hit tests,
/// and tracks hover enter/leave transitions.
#[derive(Debug, Default, Clone)]
pub struct HitTestManager {
    hitboxes: Vec<HitBox>,
    currently_hovered: Option<String>,
}

impl HitTestManager {
    pub fn new() -> Self {
        Self {
            hitboxes: Vec::new(),
            currently_hovered: None,
        }
    }

    /// Register or replace a HitBox by ID.
    pub fn register(&mut self, hitbox: HitBox) {
        self.unregister(&hitbox.id);
        self.hitboxes.push(hitbox);
    }

    pub fn unregister(&mut self, id: &str) -> bool {
        let initial_len = self.hitboxes.len();
        self.hitboxes.retain(|hb| hb.id != id);
        if self.currently_hovered.as_deref() == Some(id) {
            self.currently_hovered = None;
        }
        self.hitboxes.len() < initial_len
    }

    pub fn clear(&mut self) {
        self.hitboxes.clear();
        self.currently_hovered = None;
    }

    /// Spatial hit-testing for top-most hitbox at coordinate (x, y).
    /// Resolves overlapping hitboxes by highest z_index, then last registered (top of layer stack).
    pub fn hit_test(&self, x: f64, y: f64) -> Option<&HitBox> {
        let mut best_match: Option<&HitBox> = None;

        for hb in &self.hitboxes {
            if hb.rect.contains(x, y) {
                match best_match {
                    None => best_match = Some(hb),
                    Some(curr) => {
                        if hb.z_index >= curr.z_index {
                            best_match = Some(hb);
                        }
                    }
                }
            }
        }

        best_match
    }

    /// Handles cursor motion and emits hover transition events (MouseEnter / MouseLeave).
    pub fn handle_motion(&mut self, x: f64, y: f64) -> Vec<HoverEvent> {
        let mut events = Vec::new();
        let target_hb = self.hit_test(x, y);

        let new_hovered_id = target_hb.map(|hb| hb.id.clone());

        if self.currently_hovered != new_hovered_id {
            if let Some(old_id) = self.currently_hovered.take() {
                events.push(HoverEvent::MouseLeave(old_id));
            }
            if let Some(new_id) = &new_hovered_id {
                events.push(HoverEvent::MouseEnter(new_id.clone()));
            }
            self.currently_hovered = new_hovered_id;
        }

        events
    }

    pub fn currently_hovered(&self) -> Option<&str> {
        self.currently_hovered.as_deref()
    }
}


#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_rect_spatial_bounds_math() {
        let rect = Rect::new(100.0, 200.0, 50.0, 30.0);

        // Exact corners
        assert!(rect.contains(100.0, 200.0)); // Top-Left
        assert!(rect.contains(150.0, 200.0)); // Top-Right
        assert!(rect.contains(100.0, 230.0)); // Bottom-Left
        assert!(rect.contains(150.0, 230.0)); // Bottom-Right

        // Inside
        assert!(rect.contains(125.0, 215.0));

        // Outside bounds
        assert!(!rect.contains(99.9, 200.0));
        assert!(!rect.contains(150.1, 200.0));
        assert!(!rect.contains(100.0, 199.9));
        assert!(!rect.contains(100.0, 230.1));
    }

    #[test]
    fn test_multi_layer_hitbox_resolution() {
        let mut manager = HitTestManager::new();

        let base_layer = HitBox::new(
            "base_panel",
            Rect::new(0.0, 0.0, 500.0, 500.0),
            "default",
            Some("panel_click".to_string()),
        )
        .with_z_index(0);

        let button_layer = HitBox::new(
            "button_1",
            Rect::new(100.0, 100.0, 80.0, 40.0),
            "pointer",
            Some("btn1_click".to_string()),
        )
        .with_z_index(10);

        let modal_overlay = HitBox::new(
            "modal_close_btn",
            Rect::new(120.0, 110.0, 30.0, 20.0),
            "pointer",
            Some("close_modal".to_string()),
        )
        .with_z_index(100);

        manager.register(base_layer);
        manager.register(button_layer);
        manager.register(modal_overlay);

        // Point inside base panel only
        let res1 = manager.hit_test(10.0, 10.0).unwrap();
        assert_eq!(res1.id, "base_panel");

        // Point inside base panel & button 1
        let res2 = manager.hit_test(105.0, 105.0).unwrap();
        assert_eq!(res2.id, "button_1");

        // Point inside base panel, button 1, AND modal overlay (highest z_index)
        let res3 = manager.hit_test(125.0, 115.0).unwrap();
        assert_eq!(res3.id, "modal_close_btn");

        // Point outside all
        assert!(manager.hit_test(600.0, 600.0).is_none());
    }

    #[test]
    fn test_same_z_index_layer_stacking() {
        let mut manager = HitTestManager::new();

        let box1 = HitBox::new("first", Rect::new(0.0, 0.0, 100.0, 100.0), "default", None).with_z_index(5);
        let box2 = HitBox::new("second", Rect::new(0.0, 0.0, 100.0, 100.0), "default", None).with_z_index(5);

        manager.register(box1);
        manager.register(box2);

        // Later registered hitbox with same z_index wins
        assert_eq!(manager.hit_test(50.0, 50.0).unwrap().id, "second");
    }

    #[test]
    fn test_hover_state_transitions() {
        let mut manager = HitTestManager::new();

        let btn = HitBox::new("button_a", Rect::new(50.0, 50.0, 100.0, 50.0), "pointer", None);
        manager.register(btn);

        // Motion outside
        let events1 = manager.handle_motion(0.0, 0.0);
        assert!(events1.is_empty());
        assert_eq!(manager.currently_hovered(), None);

        // Motion into button_a
        let events2 = manager.handle_motion(60.0, 60.0);
        assert_eq!(events2, vec![HoverEvent::MouseEnter("button_a".to_string())]);
        assert_eq!(manager.currently_hovered(), Some("button_a"));

        // Subsequent motion inside button_a -> no new enter/leave
        let events3 = manager.handle_motion(70.0, 70.0);
        assert!(events3.is_empty());

        // Motion out of button_a
        let events4 = manager.handle_motion(200.0, 200.0);
        assert_eq!(events4, vec![HoverEvent::MouseLeave("button_a".to_string())]);
        assert_eq!(manager.currently_hovered(), None);
    }

    #[test]
    fn test_keyboard_shortcut_parsing_and_matching() {
        let sc1 = Shortcut::parse("Ctrl+Shift+T").unwrap();
        assert_eq!(sc1.modifiers, Modifiers::CTRL | Modifiers::SHIFT);
        assert_eq!(sc1.keycode, 'T' as u32);

        let sc2 = Shortcut::parse("Super + Q").unwrap();
        assert_eq!(sc2.modifiers, Modifiers::SUPER);
        assert_eq!(sc2.keycode, 'Q' as u32);

        let sc3 = Shortcut::parse("Alt + Return").unwrap();
        assert_eq!(sc3.modifiers, Modifiers::ALT);
        assert_eq!(sc3.keycode, 13);

        let mut matcher = ShortcutMatcher::new();
        matcher.bind(sc1, "open_terminal");
        matcher.bind(sc2, "close_window");

        // Test matching Press event
        let press_term = KeyEvent::Press('T' as u32, Modifiers::CTRL | Modifiers::SHIFT);
        assert_eq!(matcher.match_event(&press_term), Some("open_terminal"));

        let press_close = KeyEvent::Press('Q' as u32, Modifiers::SUPER);
        assert_eq!(matcher.match_event(&press_close), Some("close_window"));

        // Non-matching key or modifiers
        let press_wrong_mod = KeyEvent::Press('T' as u32, Modifiers::CTRL);
        assert_eq!(matcher.match_event(&press_wrong_mod), None);

        // Release event should not trigger shortcut match
        let release_event = KeyEvent::Release('T' as u32);
        assert_eq!(matcher.match_event(&release_event), None);
    }

    #[test]
    fn test_pointer_and_window_events() {
        let ptr_motion = PointerEvent::Motion(120.5, 340.2);
        let ptr_btn = PointerEvent::ButtonPress(272);
        let ptr_rel = PointerEvent::ButtonRelease(272);
        let ptr_scroll = PointerEvent::AxisScroll(0.0, -12.5);

        assert_eq!(ptr_motion, PointerEvent::Motion(120.5, 340.2));
        assert_eq!(ptr_btn, PointerEvent::ButtonPress(272));
        assert_eq!(ptr_rel, PointerEvent::ButtonRelease(272));
        assert_eq!(ptr_scroll, PointerEvent::AxisScroll(0.0, -12.5));

        let win_focus = WindowEvent::FocusIn;
        let win_unfocus = WindowEvent::FocusOut;
        let win_close = WindowEvent::CloseRequested;

        assert_ne!(win_focus, win_unfocus);
        assert_ne!(win_unfocus, win_close);
    }
}
