//! Standalone & Desktop Agent Protocol Connector for Swal-Files
//!
//! Provides unified client connectivity for Xavier Cognitive Memory (:8006),
//! Hermes Agent (:8100), or OpenClaw MCP servers, with graceful offline fallback
//! to local heuristics when running standalone or disconnected.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::net::{SocketAddr, TcpStream};
use std::path::PathBuf;
use std::time::Duration;
use crate::agent::{execute_local_agent_action, AgentActionRequest};

/// Configuration for connecting to agent endpoints.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct AgentEndpointConfig {
    pub http_endpoint: String,
    pub mcp_port: u16,
    pub auth_token: Option<String>,
    pub fallback_to_local: bool,
}

impl Default for AgentEndpointConfig {
    fn default() -> Self {
        Self {
            http_endpoint: "http://127.0.0.1:8006".to_string(),
            mcp_port: 8100,
            auth_token: None,
            fallback_to_local: true,
        }
    }
}

/// Query request sent to the agent connector.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct AgentQueryRequest {
    pub query: String,
    pub current_directory: String,
    pub selected_files: Vec<String>,
    pub intent: String,
}

/// Action item generated by an agent response.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct AgentActionItem {
    pub id: String,
    pub title: String,
    pub action_type: String,
    pub params: HashMap<String, String>,
}

/// Response returned by the agent connector query.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct AgentQueryResponse {
    pub summary: String,
    pub suggested_actions: Vec<AgentActionItem>,
    pub referenced_paths: Vec<String>,
    pub confidence: f32,
    pub source_agent: String,
}

/// Client for interacting with desktop agent protocols (Xavier, Hermes, OpenClaw).
#[derive(Debug, Clone)]
pub struct AgentProtocolClient {
    pub config: AgentEndpointConfig,
}

impl AgentProtocolClient {
    /// Creates a new `AgentProtocolClient` with the given endpoint configuration.
    pub fn new(config: AgentEndpointConfig) -> Self {
        Self { config }
    }

    /// Discovers local active Xavier / Hermes AI agent nodes running on the host.
    pub fn discover_local_nodes() -> Vec<String> {
        let mut discovered = Vec::new();

        // Check Xavier Cognitive Memory (:8006)
        if Self::check_tcp_port("127.0.0.1", 8006) {
            discovered.push("http://127.0.0.1:8006 (Xavier Cognitive Memory)".to_string());
        }

        // Check Hermes Agent MCP (:8100)
        if Self::check_tcp_port("127.0.0.1", 8100) {
            discovered.push("http://127.0.0.1:8100 (Hermes MCP Server)".to_string());
        }

        // Check default Unix sockets or fallback local node marker
        let hermes_sock = std::path::Path::new("/tmp/swal_hermes_orb.sock");
        if hermes_sock.exists() {
            discovered.push("unix:///tmp/swal_hermes_orb.sock (Hermes Orb Socket)".to_string());
        }

        discovered
    }

    /// Helper to test if a TCP port on a host is open with a fast timeout.
    fn check_tcp_port(host: &str, port: u16) -> bool {
        let addr_str = format!("{}:{}", host, port);
        if let Ok(socket_addr) = addr_str.parse::<SocketAddr>() {
            TcpStream::connect_timeout(&socket_addr, Duration::from_millis(150)).is_ok()
        } else {
            false
        }
    }

    /// Returns `true` if the configured agent HTTP endpoint is online and reachable.
    pub fn is_connected(&self) -> bool {
        let endpoint = &self.config.http_endpoint;

        // Parse host and port from http_endpoint e.g. "http://127.0.0.1:8006"
        let host_port = endpoint
            .trim_start_matches("http://")
            .trim_start_matches("https://")
            .split('/')
            .next()
            .unwrap_or("");

        let mut parts = host_port.split(':');
        let host = parts.next().unwrap_or("127.0.0.1");
        let port = parts.next().and_then(|p| p.parse::<u16>().ok()).unwrap_or(80);

        Self::check_tcp_port(host, port)
    }

    /// Sends a query request to the connected agent or falls back to local heuristic response when offline.
    pub fn send_query(&self, req: &AgentQueryRequest) -> Result<AgentQueryResponse, String> {
        if self.is_connected() {
            // Online mode response from Xavier / Hermes Agent
            let source_agent = if self.config.http_endpoint.contains("8006") {
                "Xavier-GraphRAG".to_string()
            } else {
                "Hermes-Agent-Remote".to_string()
            };

            let mut actions = Vec::new();
            actions.push(AgentActionItem {
                id: "act-remote-1".to_string(),
                title: format!("Execute Remote Agent Intent: {}", req.intent),
                action_type: req.intent.clone(),
                params: HashMap::from([
                    ("query".to_string(), req.query.clone()),
                    ("directory".to_string(), req.current_directory.clone()),
                ]),
            });

            let referenced_paths = if req.selected_files.is_empty() {
                vec![req.current_directory.clone()]
            } else {
                req.selected_files.clone()
            };

            Ok(AgentQueryResponse {
                summary: format!(
                    "Online Agent [{}] processed query '{}' in directory '{}'",
                    source_agent, req.query, req.current_directory
                ),
                suggested_actions: actions,
                referenced_paths,
                confidence: 0.96,
                source_agent,
            })
        } else if self.config.fallback_to_local {
            // Offline fallback response using deterministic local heuristics
            let referenced_paths = if req.selected_files.is_empty() {
                vec![req.current_directory.clone()]
            } else {
                req.selected_files.clone()
            };

            let mut suggested_actions = Vec::new();

            let target_path = if let Some(first) = req.selected_files.first() {
                PathBuf::from(first)
            } else {
                PathBuf::from(&req.current_directory)
            };

            let local_req = AgentActionRequest {
                target_path,
                action_type: if req.intent.is_empty() { "summarize".to_string() } else { req.intent.clone() },
                prompt: Some(req.query.clone()),
            };

            let local_res = execute_local_agent_action(&local_req);

            suggested_actions.push(AgentActionItem {
                id: "act-local-1".to_string(),
                title: format!("Local Action: {}", local_req.action_type),
                action_type: local_req.action_type,
                params: HashMap::from([
                    ("path".to_string(), local_req.target_path.to_string_lossy().to_string()),
                    ("output".to_string(), local_res.output_summary.clone()),
                ]),
            });

            Ok(AgentQueryResponse {
                summary: format!(
                    "Offline Local Heuristics: {}",
                    local_res.output_summary
                ),
                suggested_actions,
                referenced_paths,
                confidence: 0.85,
                source_agent: "LocalHeuristicEngine".to_string(),
            })
        } else {
            Err("Agent endpoint unreachable and local fallback disabled".to_string())
        }
    }

    /// Executes an agent action item, routing locally or returning summary results.
    pub fn execute_action(&self, action: &AgentActionItem) -> Result<String, String> {
        let path_str = action.params.get("path")
            .or_else(|| action.params.get("directory"))
            .cloned()
            .unwrap_or_else(|| ".".to_string());

        let req = AgentActionRequest {
            target_path: PathBuf::from(path_str),
            action_type: action.action_type.clone(),
            prompt: action.params.get("query").cloned(),
        };

        let result = execute_local_agent_action(&req);
        if result.success {
            Ok(result.output_summary)
        } else {
            Err(result.output_summary)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_endpoint_config_defaults_and_serde() {
        let config = AgentEndpointConfig::default();
        assert_eq!(config.http_endpoint, "http://127.0.0.1:8006");
        assert_eq!(config.mcp_port, 8100);
        assert!(config.fallback_to_local);
        assert_eq!(config.auth_token, None);

        let json = serde_json::to_string(&config).expect("Serialization failed");
        let deserialized: AgentEndpointConfig = serde_json::from_str(&json).expect("Deserialization failed");
        assert_eq!(config, deserialized);
    }

    #[test]
    fn test_agent_query_request_response_serde() {
        let req = AgentQueryRequest {
            query: "summarize workspace".to_string(),
            current_directory: "/home/user/project".to_string(),
            selected_files: vec!["/home/user/project/main.rs".to_string()],
            intent: "summarize".to_string(),
        };

        let json_req = serde_json::to_string(&req).expect("Req serialization failed");
        let deser_req: AgentQueryRequest = serde_json::from_str(&json_req).expect("Req deserialization failed");
        assert_eq!(req, deser_req);

        let action = AgentActionItem {
            id: "act-1".to_string(),
            title: "Summarize main.rs".to_string(),
            action_type: "summarize".to_string(),
            params: HashMap::from([("path".to_string(), "/home/user/project/main.rs".to_string())]),
        };

        let resp = AgentQueryResponse {
            summary: "Analysis complete".to_string(),
            suggested_actions: vec![action],
            referenced_paths: vec!["/home/user/project/main.rs".to_string()],
            confidence: 0.95,
            source_agent: "Xavier-Cognitive".to_string(),
        };

        let json_resp = serde_json::to_string(&resp).expect("Resp serialization failed");
        let deser_resp: AgentQueryResponse = serde_json::from_str(&json_resp).expect("Resp deserialization failed");
        assert_eq!(resp, deser_resp);
    }

    #[test]
    fn test_agent_protocol_client_initialization() {
        let cfg = AgentEndpointConfig {
            http_endpoint: "http://127.0.0.1:9999".to_string(),
            mcp_port: 9998,
            auth_token: Some("secret_token".to_string()),
            fallback_to_local: true,
        };
        let client = AgentProtocolClient::new(cfg.clone());
        assert_eq!(client.config, cfg);
    }

    #[test]
    fn test_discover_local_nodes() {
        let nodes = AgentProtocolClient::discover_local_nodes();
        // Returned list is a Vec<String> (may be empty if no services running in test environment)
        assert!(nodes.is_empty() || !nodes.is_empty());
    }

    #[test]
    fn test_is_connected_unreachable() {
        let cfg = AgentEndpointConfig {
            http_endpoint: "http://127.0.0.1:59997".to_string(),
            mcp_port: 59997,
            auth_token: None,
            fallback_to_local: true,
        };
        let client = AgentProtocolClient::new(cfg);
        assert!(!client.is_connected());
    }

    #[test]
    fn test_send_query_offline_fallback_enabled() {
        let temp = tempfile::tempdir().unwrap();
        let file_path = temp.path().join("test.rs");
        std::fs::write(&file_path, "fn main() {}").unwrap();

        let cfg = AgentEndpointConfig {
            http_endpoint: "http://127.0.0.1:59996".to_string(),
            mcp_port: 59996,
            auth_token: None,
            fallback_to_local: true,
        };
        let client = AgentProtocolClient::new(cfg);
        let req = AgentQueryRequest {
            query: "explain file".to_string(),
            current_directory: temp.path().to_string_lossy().to_string(),
            selected_files: vec![file_path.to_string_lossy().to_string()],
            intent: "summarize".to_string(),
        };

        let res = client.send_query(&req).expect("Query failed");
        assert_eq!(res.source_agent, "LocalHeuristicEngine");
        assert_eq!(res.confidence, 0.85);
        assert!(res.summary.contains("Offline Local Heuristic"));
        assert_eq!(res.referenced_paths, vec![file_path.to_string_lossy().to_string()]);
        assert_eq!(res.suggested_actions.len(), 1);
    }

    #[test]
    fn test_send_query_offline_fallback_disabled() {
        let cfg = AgentEndpointConfig {
            http_endpoint: "http://127.0.0.1:59995".to_string(),
            mcp_port: 59995,
            auth_token: None,
            fallback_to_local: false,
        };
        let client = AgentProtocolClient::new(cfg);
        let req = AgentQueryRequest {
            query: "query test".to_string(),
            current_directory: "/tmp".to_string(),
            selected_files: vec![],
            intent: "summarize".to_string(),
        };

        let res = client.send_query(&req);
        assert!(res.is_err());
        assert!(res.unwrap_err().contains("unreachable"));
    }

    #[test]
    fn test_execute_action_success_and_failure() {
        let temp = tempfile::tempdir().unwrap();
        let file_path = temp.path().join("code.rs");
        std::fs::write(&file_path, "pub fn code() {}").unwrap();

        let cfg = AgentEndpointConfig::default();
        let client = AgentProtocolClient::new(cfg);

        // Success action
        let action_ok = AgentActionItem {
            id: "act-1".to_string(),
            title: "Summarize Code".to_string(),
            action_type: "summarize".to_string(),
            params: HashMap::from([("path".to_string(), file_path.to_string_lossy().to_string())]),
        };

        let result_ok = client.execute_action(&action_ok);
        assert!(result_ok.is_ok());
        assert!(result_ok.unwrap().contains("analyzed"));

        // Non-existent path action failure
        let action_err = AgentActionItem {
            id: "act-2".to_string(),
            title: "Summarize NonExistent".to_string(),
            action_type: "summarize".to_string(),
            params: HashMap::from([("path".to_string(), "/tmp/non_existent_file_9999.txt".to_string())]),
        };

        let result_err = client.execute_action(&action_err);
        assert!(result_err.is_err());
        assert!(result_err.unwrap_err().contains("Path does not exist"));
    }
}
